<?php

/**
 * site_master
 * @var $faker \Faker\Generator
 * @var $index integer
 */
return [
    'site_master_id' => $faker->numberBetween(1, 2),
    'widget_name' => $faker->text(20),
    'element1' => $faker->numberBetween(0, 5),
    'element2' => $faker->numberBetween(0, 5),
    'element3' => $faker->numberBetween(0, 5),
    'element4' => $faker->numberBetween(0, 5),
    'valid_chk' => $faker->numberBetween(0, 1),
    'widget_layout_id' => $faker->numberBetween(1, 10),
    'sort' => $faker->randomNumber(),
    'id' => $index + 1,
    'tenant_id' => $faker->numberBetween(1, 2),
    'site_master_id' => $faker->numberBetween(1, 2),
    'site_name' => $faker->realText(255),
    'company_name' => $faker->realText(255),
    'tanto_name' => $faker->realText(255),
    'support_tel_no' => $faker->realText(255),
    'site_url' => $faker->realText(255),
    'site_title' => $faker->realText(255),
    'meta_description' => $faker->realText(255),
    'meta_keywords' => $faker->realText(255),
    'support_mail_name' => $faker->realText(255),
    'support_mail_address' => $faker->email,
    'support_mail_subject' => $faker->realText(255),
    'application_mail_name' => $faker->realText(255),
    'application_mail_address' => $faker->realText(255),
    'application_mail_subject' => $faker->realText(255),
    'regist_mail_name' =>$faker->realText(255),
    'regist_mail_address' => $faker->email,
    'regist_mail_subject' => $faker->realText(255),
    'password_mail_name' => $faker->realText(255),
    'password_mail_address' => $faker->email,
    'password_mail_subject' => $faker->realText(255),
    'expo_mail_name' => $faker->realText(255),
    'expo_mail_address' => $faker->email,
    'expo_mail_subject' => $faker->realText(255),
    'job_mail_name' => $faker->realText(255),
    'job_mail_address' => $faker->email,
    'job_mail_subject' => $faker->realText(255),
    'friend_mail_name' => $faker->realText(255),
    'friend_mail_address' => $faker->email,
    'friend_mail_subject' => $faker->realText(255),
    'mail_sign' => $faker->tinyText(),
    'review_required' => $faker->tinyInt(1),
    'review_mail_name' => $faker->realText(255),
    'review_mail_address' => $faker->email,
    'review_mail_subject' => $faker->realText(255),
    'application_required' => $faker->tinyInt(1),
    'webmail_required' => $faker->tinyInt(1),
    'scout_use' => $faker->tinyInt(1),
    'member_use' => $faker->tinyInt(1),
    'smart_site_title' => $faker->realText(255),
    'smart_meta_description' => $faker->realText(255),
    'smart_meta_keywords' => $faker->realText(255),
    'adoption_reminder_day' => $faker->int(11),
    'auto_adoption_day' => $faker->int(11),
    'area_pref_flg' => $faker->tinyInt(1),
    'encryption_flg' => $faker->tinyInt(1),
    'login_ssl_required' => $faker->tinyInt(1),
    'alert_job_num_flg' => $faker->tinyInt(1),
    'alert_job_num_limit' => $faker->int(11),
];
