<?php

namespace app\modules\manage\controllers\secure;

use Yii;
use app\models\manage\EmploymentTypeCd;

/**
 * EmploymentController implements the CRUD actions for EmploymentTypeCd model.
 */
class EmploymentController extends SearchKeyBaseController
{
    public function init()
    {
        $this->groupModel = new EmploymentTypeCd();

        $this->attribute = [
            'firstName' => 'employment_type_name',
            'page' => 'employment',
        ];

        return parent::init(); // TODO: Change the autogenerated stub
    }
}