<?php

namespace app\modules\manage\controllers\secure;

use app\models\manage\searchkey\JobTypeBig;
use app\models\manage\searchkey\JobTypeCategory;
use app\models\manage\searchkey\JobTypeSmall;
use Yii;

/**
 * JobTypeController implements the CRUD actions for JobTypeCategory model.
 */
class JobtypeController extends SearchKeyBaseController
{
    public function init()
    {
        $this->groupModel = new JobTypeCategory();
        $this->cateModel = new JobTypeBig();
        $this->itemModel = new JobTypeSmall();

        $this->attribute = [
            'dropDownList' => [$this->groupModel->getJobTypeCategoryList(), $this->cateModel->getJobTypeBigList()],
            'relation' => ['jobTypeBig', 'jobTypeSmall'],
            'page' => 'jobtype',
        ];

        return parent::init(); // TODO: Change the autogenerated stub
    }
}