<?php
namespace app\modules\manage\controllers\secure;

use Yii;
use app\models\manage\SearchkeyCategory1;
use app\models\manage\SearchkeyItem1;

/**
 * MeritController implements the CRUD actions for MeritCategoryCd model.
 */
class MeritController extends SearchKeyBaseController
{
	public function init()
	{
		$this->groupModel = new SearchkeyCategory1();
		$this->cateModel = new SearchkeyItem1();

		$this->attribute = [
				'groupId' => 'searchkey_category1_id',
				'relationName' => ['relation1'],
				'dropDownList' => [$this->groupModel->getSearchkeyCategory1List(false)],
				'page' => 'search1',
		];

		return parent::init(); // TODO: Change the autogenerated stub
	}
}