<?php

namespace app\modules\manage\controllers\secure;

use Yii;
use app\models\manage\OccupationCd;

/**
 * OccupationController implements the CRUD actions for OccupationCd model.
 */
class OccupationController extends SearchKeyBaseController
{
    public function init()
    {
        $this->groupModel = new OccupationCd();

        $this->attribute = [
            'firstName' => 'occupation_name',
            'page' => 'occupation',
        ];

        return parent::init(); // TODO: Change the autogenerated stub
    }
}