<?php

namespace app\modules\manage\controllers\secure;

use yii;

/**
 * 管理画面->項目管理ｰ>応募者項目設定->一覧画面　コントローラー
 */
class OptionApplicationController extends OptionBaseController
{
    public function init()
    {
        $this->functionItemSetMenu = 'application';
        return parent::init(); // TODO: Change the autogenerated stub
    }
}