<?php

namespace app\modules\manage\controllers\secure;

use yii;

/**
 * 管理画面->項目管理ｰ>管理者項目設定　コントローラー
 */
class OptionAdminController extends OptionBaseController
{
    public function init()
    {
        $this->functionItemSetMenu = 'admin';
        return parent::init(); // TODO: Change the autogenerated stub
    }
}
