<?php

namespace app\modules\manage\controllers\secure;

use yii;

/**
 * 管理画面->項目管理ｰ>求人原稿項目設定　コントローラー
 */
class OptionJobController extends OptionBaseController
{
    public function init()
    {
        $this->functionItemSetMenu = 'job';
        return parent::init(); // TODO: Change the autogenerated stub
    }
}
