<?php

namespace app\modules\manage\controllers\secure;

use Yii;
use app\models\manage\searchkey\PrefDistMaster;
use app\models\manage\searchkey\PrefDist;
use app\models\manage\searchkey\Dist;
use yii\db\Exception;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\bootstrap\ActiveForm;

/**
 * PrefdistController implements the CRUD actions for PrefDistMaster model.
 */
class PrefdistController extends SearchKeyBaseController
{
    public function init()
    {
        $this->groupModel = new PrefDistMaster();
        $this->cateModel = new PrefDist();

        $this->attribute = [
            'page' => 'prefdist',
        ];

        return parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 一覧ページ
     * @return mixed
     */
    public function actionList()
    {
        //新規登録モーダル用(１階層）
        //地域グループモデル
        /** @var PrefDistMaster $newFirstModel */
        $newFirstModel = $this->createModel('first');

        //更新モーダル用(１階層）
        //地域グループモデル
        $updateFirstProvider = $newFirstModel->search($this->get);

        //一覧モデル
        $leftListModel = $newFirstModel->findAllOrdered();
        $rightListModel = Dist::listFind($this->get);

        return $this->render('list', [
            'newFirstModel' => $newFirstModel,
            'updateFirstProvider' => $updateFirstProvider,
            'attribute' => $this->attribute,
            'leftlistmodel' => $leftListModel,
            'rightlistmodel' => $rightListModel,
        ]);
    }

    /**
     * Updates an existing model.
     * 地域グループに紐づく市区町村を更新する
     * @return mixed
     */
    public function actionUpdatePrefDist()
    {
        $transaction = Yii::$app->db->beginTransaction();
        try {
            if(Yii::$app->request->get('PrefDist') != null) {

                foreach(Yii::$app->request->get('PrefDist') as $key => $value):
                    if (empty($key)) {
                        continue;
                    }
                    //地域グループ取得
                    $model = $this->findModel($key, 'first');

                    //まず既存データを削除する
                    $model->unlinkAll('prefDist', true);

                    //地域グループに市区町村を登録する
                    foreach (explode(',',$value) as $id) {
                        if (empty($id)) {
                            continue;
                        }
                        $prefDist = new PrefDist();
                        $prefDist->pref_dist_master_id = $key;
                        $prefDist->dist_id = $id;
                        $model->link('prefDist', $prefDist);
                    }

                endforeach;
            }
            $transaction->commit();

            //メッセージ作成
            $this->session->setFlash('operationComment', Html::tag('p', Yii::t('app', '更新が完了しました。'), ['class' => 'alert alert-warning']));

            //登録成功
            return $this->redirect(Url::toRoute(array_merge(['list'], ['PrefDistMaster' => Yii::$app->request->get('PrefDistMaster')])));

        } catch (Exception $e) {
            //todo 例外処理のエラーメッセージなど決まれば修正する
            //登録失敗
            $transaction->rollBack();
            return $this->redirect(['list?error=true2']);
        }
    }

    /**
     * 地域グループ登録用モーダルを非同期表示するためのアクション
     * @param int $id PrefDistMasterのid
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionPjaxModal($id = null)
    {
        $model = PrefDistMaster::findOne(['id' => $id]);
        if(!$model){
            $model = new PrefDistMaster();
        }

        return $this->renderAjax('/secure/common/_searchkey-form', [
            'model' => $model,
            'flg' => 'first',
            'isNew' => $model->isNewRecord,
            'attribute' => ['page' => 'prefdist'],
        ]);
    }

    /**
     * フォーム画面検証用のajaxバリデーションアクション
     * @param $id
     * @return array
     */
    public function actionAjaxValidation($id)
    {
        if ($id) {
            $model = PrefDistMaster::findOne(['id' => $id]);
        } else {
            $model = new PrefDistMaster();
            // 詳細な原因は不明だが、下記コードが無いと、pref_dist_nameのuniqueバリデーションが正常に動作しない場合がある。
            // 正常に動作しない場合は下記コードのコメントを外して実行すること。
            $model->pref_id = Yii::$app->request->post('PrefDistMaster')['pref_id'];
        }
        $model->load($this->post);
        Yii::$app->response->format = Response::FORMAT_JSON;
        return ActiveForm::validate($model);
    }
}