<?php

namespace app\modules\manage\controllers\secure;

use Yii;
use app\models\manage\searchkey\WageCategory;
use app\models\manage\searchkey\WageItem;

/**
 * WageController implements the CRUD actions for WageTypeMaster model.
 */
class WageController extends SearchKeyBaseController
{
    public function init()
    {
        $this->groupModel = new WageCategory();
        $this->cateModel = new WageItem();

        $this->attribute = [
            'groupId' => 'wage_category_id',
            'dropDownList' => [$this->groupModel->getWageCategoryList()],
            'relation' => 'wageItem',
            'page' => 'wage',
        ];

        return parent::init(); // TODO: Change the autogenerated stub
    }
}