<?php

namespace app\modules\manage\controllers\secure;

use Yii;
use app\models\manage\WorkGroupCd;
use app\models\manage\WorkHourCd;

/**
 * WorktimeController implements the CRUD actions for WorkGroupCd model.
 */
class WorktimeController extends SearchKeyBaseController
{
    public function init()
    {
        $this->groupModel = new WorkGroupCd();
        $this->cateModel = new WorkHourCd();

        $this->attribute = [
            'groupId' => 'id',
            'firstName' => 'work_group_cd',
            'secondName' => 'work_hour_cd',
            'relationName' => ['wageCds'],
            'dropDownList' => [$this->groupModel->getWageTypeList(false)],
            'page' => 'wage',
        ];

        return parent::init(); // TODO: Change the autogenerated stub
    }
}